{% set name = "willow" %}
{% set version = "1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/willow-{{ version }}.tar.gz
  sha256: b3aa13f0dc259b6ac76d52778756157a2abcfb59eb08db6472701d78e21dcf33

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - flit_core >=3.2,<4
    - pip
  run:
    - python >=3.8
    - filetype >=1.0.10,!=1.1.0
    - defusedxml >=0.7,<1.0

test:
  imports:
    - willow
  commands:
    - pip check
  requires:
    - pip

about:
  summary: A Python image library that sits on top of Pillow, Wand and OpenCV
  dev_url: https://github.com/wagtail/Willow
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - darynwhite
