{% set name = "willow" %}
{% set version = "1.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/willow-{{ version }}.tar.gz
  sha256: 70292b2d0cd2d5bb4076f0b3d61308aeaa0b225f3970d00752f08a8fd386c3d1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.2,<4
    - pip
  run:
    - python >={{ python_min }}
    - filetype >=1.0.10,!=1.1.0
    - defusedxml >=0.7,<1.0
    - Pillow >=9.1.0,<12.0.0
  run_constrained:
    - Wand >=0.6,<1.0
    - pillow-heif >=0.10.0,<0.22.0 # py<312
    - pillow-heif >=0.13.0,<0.22.0 # py>=312

test:
  imports:
    - willow
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/wagtail/Willow
  license: BSD-3-Clause
  license_family: BSD
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: A unified interface to Python image libraries
  description: Willow is a simple image library that combines the APIs of Pillow, Wand and OpenCV. It converts the image between the libraries when necessary.
  doc_url: http://willow.readthedocs.io/en/latest/
  dev_url: https://github.com/wagtail/Willow

extra:
  recipe-maintainers:
    - darynwhite
